### ISSUE TITLE
Add the ability to provide own logger instance

### ISSUE THREAD

**Issue by Kopo942** [slimjar/slimjar#42]
Also from #36, for tracking purposes.

It would be great to be able to provide my own Logger instance to SlimJar, since many platforms don't log `fine` level logs and it's sometimes a hassle to change the log level of the parent logger.

**Comment by Vshnv** [comment]
Hi,
This feature is currently being implemented in the `feature/logging` branch and is planned to be released with the `1.2.5` patch. We have published a snapshot version for trial. Could you please try out the [latest snapshot version](https://repo.vshnv.tech/snapshots/io/github/slimjar/slimjar/1.2.5-SNAPSHOT) `1.2.5-SNAPSHOT` and let us know if it meets your expectations?

Usage Example
```java
ApplicationBuilder#logger((message, arguments) -> /* Call the logger implementation used by you */ )...
```
The `LoggerProcess` also provides another method called `debug` which prints even more detailed logs. To use it you would need to use the anonymous class syntax instead of a lambda.

```java
ApplicationBuilder#logger(new ProcessLogger() {
            @Override
            public void log(String message, Object... args) {
                /* Call the logger implementation used by you */
            }

            @Override
            public void debug(String message, Object... args) {
                 /* Call the logger implementation used by you for detailed debug messages */
            }
})...
```

**Comment by Kopo942** [comment]
Usage example looks great, thank you! Does `1.2.5-SNAPSHOT` not work in `gradle.properties`? Gradle is unable to solve the dependency for me.

**Comment by Vshnv** [comment]
It should work. Try adding `https://repo.vshnv.tech/snapshots` as a separate repository.

**Comment by Kopo942** [comment]
>let us know if it meets your expectations?

The logging works wonderfully and is very easy to implement, thank you very much for the quick addition of this feature! :)

**Comment by Kopo942** [comment]
https://github.com/slimjar/slimjar/blob/feature/logging/slimjar/src/main/java/io/github/slimjar/resolver/CachingDependencyResolver.java#L61
There seems to be a bug here since an object reference is being logged:
![image](https://user-images.githubusercontent.com/13612979/126070807-6ea16ec0-8fc4-425b-9d8b-b70724b32add.png)

**Comment by Vshnv** [comment]
Ah, my bad, Ill get to fixing that now. 
Thank you
